community/phantomjs/PKGBUILD

This has been tested working on armv7h. It needs testing on the other platforms.
The fixes are ported from the qt4 PKGBUILD (phantomjs bundles Qt). It appears that -fno-strict-volatile-bitfields is no longer needed.

Added phantomjs fixes for ARM

---

alarm/uboot-sunxi/PKGBUILD

Add u-boot-sunxi target for A20-OLinuXino-Lime2 board.

[uboot-sunxi] add a20-olinuxino-lime2

---

core/linux-imx6-cubox-dt/PKGBUILD
core/linux-imx6-cubox-dt/config

This will create /dev/spidev1.0 and /dev/spidev1.1 on the HummingBoard.
SPI requires modifications to the current dtb files, which can be seen in
https://github.com/SolidRun/linux-imx6-3.14/pull/19

Enable spidev kernel module for use with HummingBoard

---

core/linux-raspberrypi/PKGBUILD
core/linux-raspberrypi/config.v6
core/linux-raspberrypi/config.v7

it can be used in trasmission to avoid saturate the bandwidth.
see http://www.pps.univ-paris-diderot.fr/~jch/software/bittorrent/tcp-congestion-control.html

core/linux-raspberrypi: Add support for tcp_lp module

---

alarm/kodi-rbp/PKGBUILD

ALSA support is needed for other audio devices like USB and the HiFiBerry. Tested and confirmed that on-board audio still works and USB audio works as well.

enable ALSA support

---

core/linux-raspberrypi/PKGBUILD
core/linux-raspberrypi/config.txt

* fix wrong name of overlay for w1-gpio using external pullup
* update w1-gpio(-pullup) parameters according to /boot/overlays/README

core/linux-raspberrypi: Update Device Tree config

---

core/linux-kirkwood-dt/PKGBUILD

When ${cryptodev-commit} changes, local name for the source tarball
should change too, otherwise source caching will break.
I did not bump $pkgrel because the created package won't change, so no point to "upgrade" to it.

core/linux-kirkwood-dt: Fix cryptodev source local naming

---

core/linux-kirkwood-dt/PKGBUILD

Fix typo introduced in commit 571b9ac25791e48035c91e5990d083266b6796eb
Sorry, my bad.

core/linux-kirkwood-dt: Fix typo

---

core/linux-armv7/PKGBUILD

linux-armv7-3.19.1-2 still provides 3.19.0 as the patch providing the point release hasn't been considered in PKGBUILD again.

core/linux-armv7: fix point release 3.19.1

---

alarm/weston-rpi/PKGBUILD

This package builds weston with the Raspberry Pi compositor on armv7h too.
As a matter of fact the weston package from community only support
the Raspberry Pi armv6h models, hence this package is needed for
proper Raspberry Pi 2 support.

Add alarm/weston-rpi

---

core/linux-am33x-legacy/PKGBUILD
core/linux-am33x/PKGBUILD
core/linux-armv7-rc/PKGBUILD
core/linux-armv7/PKGBUILD

I have a new dedicated box running rcn-ee.com, to prevent any possible
downtime as i move rcn-ee.net over, switch to the .com now.
btw: https is also available, if you want to eventually enable that too.
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

server: bb.org: migrate rcn-ee.net to rcn-ee.com

---

core/linux-odroid-c1/PKGBUILD

This fixes an issue with the mali driver fbdev support.

core/linux-odroid-c1 to 3.10.72-3

---

alarm/ti-uim/PKGBUILD

As gitorious was aquired by gitlab and they might shutdown gitorious.org
I created a backup of the git repo on my github account: `git://github.com/asdil12/ti-uim.git`
This PR just adds the above note as a comment to the PKGBUILD file.

ti-uim: provide backup repo url (as a comment)

---

alarm/gpu-viv-g2d/PKGBUILD

The next version of Kodi for imx will have a significant rewrite of the graphics and video playback.  The 2d hardware support will become required in future versions of Kodi.  This pull request adds a package which just contains the vivante g2d library, header and licence.  It is based on the gpu-viv-bin-mx6q PKGBUILD.

Add alarm/gpu-viv-g2d: Vivante G2D package

---

alarm/dkms-mt7610/PKGBUILD
alarm/dkms-mt7610/dkms-mt7610.install
alarm/dkms-mt7610/dkms.conf

Hey guys,
I've recently bought a Raspberry Pi 2 and attached a `MT7610U`/`AC600` [5Ghz nano USB dongle](http://www.amazon.co.uk/dp/B00VHB0EW0).
This dkms-module supports these chipsets:
* `mt7650u`
* `mt7630u`
* `mt7610u`
It's using the official [Mediatek](http://www.mediatek.com/en/downloads/mt7601u-usb/) driver along with two other patches:
* `kuid_t-kgid_t.patch`
* `__DATE__ & __TIME__macro-warning.patch`
to fix compilation issues.
P.S.: The link is good, check the description of the driver. There's an URL error on Mediatek's website.
[mt7610u](http://www.mediatek.com/en/downloads/mt7601u-usb/) & [mt7601u](http://www.mediatek.com/en/downloads/mt7610u-usb/) are switched.

support for Ralink mt7610U

---

extra/intel-tbb/PKGBUILD

Hi,
I have added the intel-tbb package from upstream extra repo to be able to compile opencv with TBB support.
Tested on Raspberry Pi 2 and Odroid C1.
I have only added the armv7h architecture and specials CXXFLAGS for it.
It is my first PKGBUILD so tell me if I did anything wrong.
Thank you.

Add extra/intel-tbb for armv7h

---

alarm/weston-rpi/PKGBUILD

libinput changed ABI so the old weston doesn't run.
Increase the release to make a new build with the new libinput happen.

alarm/weston-rpi: Increase release for rebuild

---

alarm/dkms-mt7601/PKGBUILD
alarm/dkms-mt7601/dkms-mt7601.install
alarm/dkms-mt7601/dkms.conf

I had been making fixes to my own copy of the source, but this new
upstream does it better.
I've started with the AUR mt7601-git PKGBUILD, and added dkms.
I also fixed dkms to actually work.

dkms-7601: Changed upstream source to https://github.com/porjo/mt7601

---

alarm/parallella-firmware/PKGBUILD

This adds two new packages for the [updated] headless 7010/7020 parallella bitstreams.
This is based on the 2015.1 release, which only provides the headless variants. HDMI variants can be added once those bitstreams are hosted somewhere.
This also removes the older alarm/parallella-firmware package as it is out of date.
These packages provide/conflict "parallella-firmware" and the hope is a user can install whichever matches their board by selecting {HDMI,headless}-{7010,7020}

alarm/parallella-firmware: add updated headless 7010/7020 variants

---

alarm/weston-rpi/PKGBUILD

Weston 1.8.0 was released on [June 2, 2015](http://lists.freedesktop.org/archives/wayland-devel/2015-June/022416.html).

Update Weston to 1.8.0.

---

core/linux-peach/PKGBUILD
core/linux-veyron/PKGBUILD

SKIP was already implemented for `linux-chromebook2`, but after the rewrite to `linux-peach` and after `-veyron` was created the packages lost this property. However the chromeos git servers are still annoyingly nondeterministic, so if `makepkg` is called without `--skipinteg` it will most likely fail.
I do not update the pkgrels as my changes do not affect the resulting packages.

core/linux-{peach,veyron}: md5sums should SKIP the nondeterministic kernel tar.gz

---

alarm/kodi-imx/PKGBUILD

srp 06 15:22:35 cubox.lan systemd[1]: Starting Starts an instance of Kodi...
srp 06 15:22:35 cubox.lan systemd[1]: Started Starts an instance of Kodi.
srp 06 15:22:36 cubox.lan kodi-standalone[333]: /usr/lib/kodi/kodi.bin: error while loading shared libraries: libfreetype.so.6: cannot open shared object file: No such file or directory
srp 06 15:22:36 cubox.lan kodi-standalone[333]: /usr/lib/kodi/kodi.bin: error while loading shared libraries: libfreetype.so.6: cannot open shared object file: No such file or directory
srp 06 15:22:36 cubox.lan kodi-standalone[333]: /usr/lib/kodi/kodi.bin: error while loading shared libraries: libfreetype.so.6: cannot open shared object file: No such file or directory
srp 06 15:22:36 cubox.lan kodi-standalone[333]: /usr/bin/kodi --standalone -l …

kodi-imx missing freetype2 dep

---

alarm/uboot-odroid/PKGBUILD

Tested on ODroid U2 with Linux-armv7-rc, works great.
U-boot 2015.04 (the old version) had issues with the USB controller initialisation in Linux for me, and would only work when 'usb start' was commented out in the boot command.

Updated U-boot for ODroid to 2015.07

---

alarm/kodi-imx/PKGBUILD
alarm/kodi-imx/kodi.service

When messages are added to dmesg they're shown in kodi as overlay. In order to disable this behaviour the service script disable dmesg console logging before start of kodi and reenable console logging after. Since this operation needs root rights the PermissionsStartOnly was set to true.

alarm/kodi-imx - disabled kodi showing dmesg messages

---

community/mpv/PKGBUILD

mpv supports egl video output but it has to be specifically enabled by configure.
Since version 0.10.0 the 'x11' video output module has been removed.
On an odroid at least the 'xv' video output module does not work so without the egl module no video output seems possible.
The actual command line switch to enable the egl video output is not that easy to find and I considered adding a message in the .install file. I can add it if you like.
For the record it is
`--vo=opengl:backend=x11egl:es`
I've tested this with the (Mali) egl/gles libraries removed from my device, and it does still build. In fact the egl output still works (via mesa, with poor quality). So this pull release should have no impact on devices without egl/gles.

mpv: Enable egl video output

---

alarm/libcec-imx6/PKGBUILD

This fixes Pulse-Eight/libcec#112 via Pulse-Eigth/libcec@2f32a9debc1f148b5dfcfc463480f1432bb71725.
My initial patch was missing a PKGREL update, should be fixed now.

alarm/libcec-imx6: fix compilation in non-git paths

---

community/nodejs/PKGBUILD

On my Marvell Armada 370 based NAS nodejs was crashing with Illegal instruction error.
Investigating with gdb I identified the problem to be the Armada 370 FPU. The Armada 370 has a 16 register vfpv3-d16 compatible FPU. This updates the nodejs config to be compatible with vdpv3-d16 CPUs. Tested on my Armada 370 device.
$ gdb node
...
(gdb) disassemble $pc,$pc+8
Dump of assembler code from 0x22f0a214 to 0x22f0a21c:
=> 0x22f0a214:    vpushne    {d16-d31}
0x22f0a218:    subeq    sp, sp, #128    ; 0x80

Configure nodejs for vfpv3-d16 FPUs.

---

alarm/libcec-rpi/PKGBUILD

This fixes https://github.com/Pulse-Eight/libcec/issues/112 via https://github.com/Pulse-Eight/libcec/commit/2f32a9debc1f148b5dfcfc463480f1432bb71725 .
Same as for other platform from https://github.com/archlinuxarm/PKGBUILDs/pull/1276
Problems without this patch and pkgrel bump:
```
$ cec-client -l
cec-client: symbol lookup error: /usr/lib/libcec.so.3.0: undefined symbol: _ZN11StringUtils6FormatEPKcz
$
```
Build testet directly on Raspberry Pi 2, there was need for 'arch=('armv7h') ':
==> Finished making: libcec-rpi 3.0.1-3 (Thu Dec 17 23:31:49 CET 2015)
The 'cec-client -l' is again working:
```
$ cec-client -l
libCEC version: 3.0.1, git revision: <unknown>, compiled on Thu Dec 17 22:25:46 UTC 2015 by crow@vdrrpi on Linux 4.1.15-1-ARCH (armv7l), features: P8_USB, P8_detect, randr, 'RPi' …
```

alarm/libcec-rpi: fix compilation in non-git paths

---

alarm/kodi-rbp-git/PKGBUILD

This applies commit 6e7c288 to the kodi-rbp-git package to avoid the crash with a SIGBUS error as mentioned here: http://archlinuxarm.org/forum/viewtopic.php?f=15&t=9599.
Without this patch, this package is currently unusable on Armv7h as Kodi immediately crashes on startup.

[alarm/kodi-rbp-git] Apply CXX11_ABI to fix SIGBUS crash

---

core/linux-peach/linux-peach.install

There was a superfluous adding of the string "/dev/" to the output path for the manual instructions to dd the new kernel in place.
I did not bump pkver/pkrel as I think this change does not warrant a new release. (It does not affect people that already installed the package.)
Old erroneous behavious for reference:
```
6/8) Aktualisiere linux-peach                                                                       [############################################################] 100%
>>> Updating module dependencies. Please wait ...
A new kernel version needs to be flashed onto /dev/mmcblk0p1.
Do you want to do this now? [y|N]
N
You can do this later by running:
```

[linux-peach] fixed path for manual kernel update

---

core/glibc/PKGBUILD
core/glibc/glibc.install

locale-gen is now called on each update. The update to 2.22-4 broke locales
so force an update by raising the pkgrel to 4.1.

glibc: sync install script with Arch Linux [core]

---

core/linux-imx6/PKGBUILD
core/linux-imx6/fix_cec_revb1.patch

To enable CEC on Rev B1 follow this guide: https://project-insanity.org/blog/2014/01/24/wandboard-with-hdmi-cec-and-xbmc/

core/linux-imx6: Fix CEC for first Wandboard Quad Revision

---

community/mongodb/PKGBUILD

By default, MongoDB 3.2.5 dropped the only storage engine that was available on 32-bits ARM platforms : `mmapv1`. This prevents MongoDB from working properly as seen [on the forums](https://archlinuxarm.org/forum/viewtopic.php?f=15&t=10236).
This commit forces mmapv1 to be included on all ARM platforms, so that MongoDB works properly even straight out of the box. Indeed, on first start, MongoDB will try to initialize the database using the storage engine in the configuration file (`mmapv1`), which was not included by default.

 MongoDB: Force mmapv1 to be compiled in

---

alarm/cryptodev-dkms/dkms.conf

cryptodev would only have been built for the currently running kernel, since the environment variable wasn't being overridden to specify the target kernel

[cryptodev-dkms] Properly set DKMS kernel target

---

core/linux-odroid-xu3/PKGBUILD
core/linux-odroid-xu3/exynos-gcc6.patch

This kernel currently doesn't build under gcc6 due to the position of an enum declaration in `exynos-ss.c`. This patch resolves the issue, and the kernel builds successfully under gcc 6.1.1.

core/linux-odroid-xu3: Add patch to exynos-ss for build under gcc6

---

alarm/uboot-odroid-c2/PKGBUILD
alarm/uboot-odroid-c2/boot.ini

Newer kernels allows controlling the HDMI PHY on/off state.

alarm/uboot-odroid-c2 to 2015.01-12

---

community/dart/PKGBUILD

First time trying to commit to this project so if I am doing something wrong please tell me.
The Dart PKGBUILD in Arch Linux is not compatible with Arch Linux ARM because the PKGBUILD is downloading the binary files (x86/x86_64) directly from the Dart project.
This pull request changes the PKGBUILD to be able to download the ARMv7h version from the Dart project. I don't know if this version works with ARMv8 since I do not own such board so I have added "buildarch=4" to the PKGBUILD.
Tested on Beaglebone Black.

add community/dart

---

alarm/uboot-cubox-i/PKGBUILD
alarm/uboot-cubox-i/kernel-add-support-for-gcc-6.patch

No version bump to avoid useless compilation and reflashing.
Signed-off-by: Jérôme Benoit <jerome.benoit@piment-noir.org>

alarm/uboot-cubox-i: build fix for gcc6

---

alarm/kodi-odroid/PKGBUILD
alarm/kodi-odroid/kodi.install

I have been heavily testing it on my Odroid U3 for over 2 weeks and it works great for me.
Since all dependencies are Odroid X/X2/U2/U3 specific, I suppose, it should work on those devices as well.
The PKGBUILD is based on kodi-c1 PKGBUILD.
NOTE: MFC firmware couldn't have been found on my Odroid U3 because the `s5p-mfc*.fw` files are installed into `/lib/firmware/`, but once I symlinked these `*.fw` files to `/lib/firmware/s5p-mfc/` folder, it worked like a charm (see details here: https://archlinuxarm.org/forum/viewtopic.php?f=60&t=10913). This issue is not related to the packaging, but it is related to the user experience.

alarm/kodi-odroid new package (17.0.beta4)

---

alarm/kodi-rbp-git/99-kodi.rules
alarm/kodi-rbp-git/PKGBUILD

Addition of a set of udev rules allowing the video group access to the following required for accelerated video playback.  For rationale see: http://forum.kodi.tv/showthread.php?tid=295230

alarm/kodi-rbp-git: add udev rules to allow video group access to play older files

---

alarm/kodi-rbp-git/PKGBUILD

Standardized the use of quotes and variables through out the PKGBUILD.  The configure step contained options that are defaulted either by an auto settings that will pick them up based on the dependencies or that are hard coded into configure so remove them.  In one case, an option as defined twice (pulse).  Changes build fine and lead to a functional package on RPi3.

alarm/kodi-rbp-git: fixup PKGBUILD

---

alarm/kodi-rbp/PKGBUILD
alarm/kodi-rbp/kodi.service

* Fixes transparent black boarders when used as systemd service
* Added gdb as optional dependency for stack traces
* Start kodi after lircd service to ensure lircd runs first
* Fixed a polkit permission warning when installing the package
-> Those changes should also be adopted to the -git package possibly.

alarm/kodi-rbp to 16.1-5

---

alarm/kodi-rbp-git/99-kodi.rules
alarm/kodi-rbp-git/PKGBUILD
alarm/kodi-rbp-git/kodi.install

Changes introduced:
* udev rule to enable keyboard to work
* modification of kodi user on install to be in tty and input groups
Why needed:
* USB keyboards do not work out-of-the-box without this modification
Note:
* If approved, this should be backported to [alarm]/kodi-rbp as well.

[kodi-rpb-git] - allow USB keyboard to work out-of-the-box

---

alarm/kodi-rbp-git/PKGBUILD

Changes introduced:
* Include patches from popcornmix's branch of kodi to solve issue of video tearing on playback of some video files.
Why needed:
* VIdeo files encoded with GMC (global motion compensation) cause the problem on RPi3.  The patches switch to software decoding mode when GMC is detected to avoid the tearing without user intervention and are including in LibreELEC and OSMC.
> Due to the extra decoding CPU cost of global motion compensation, most hardware players do not support global motion compensation.
Verified to solve the tearing issue on my box; non-GMC files seem to play just fine for the 5 that I tested.
[Link](http://forum.kodi.tv/showthread.php?tid=297524) to kodi forum thread for additional background info.

alarm/kodi-rpb-git: switch to software decode for GMC files

---

alarm/kodi-rbp-git/PKGBUILD

Beta 6 was released and this PR should bring out package up to this version.

alarm/kodi-rbp-git: update to 17.0v6

---

alarm/xf86-video-fbturbo-odroid-c2-git/PKGBUILD

Currently, this fbturbo driver is faster than the mali driver on odroid-c2. I added a new package entirely based on the [current xf86-video-fbturbo-git PKGBUILD](https://github.com/archlinuxarm/PKGBUILDs/blob/master/alarm/xf86-video-fbturbo-git/PKGBUILD).

odroid-c2: added xf86-video-fbturbo-odroid-c2-git package

---

alarm/kodi-odroid/PKGBUILD

I have been running this version with no glitches on my Odroid U3 for 3 days.
I have also enabled the missing in the previous version [CEC support](http://kodi.wiki/view/CEC#Settings_in_Kodi_for_CEC).

alarm/kodi-odroid to 17.0.beta7

---

alarm/kodi-rbp-git/PKGBUILD

The PR will allow libcec to be optional rather than required as it is with the official package.  On some systems, the kodi.log can be spammed with megabytes of errors if the using the 3.5mm jack for other autio output while the HDMI is connected to the TV.
I have been running this as-is without ill effect.

alarm/kodi-rbp-git: update to 17.0rc2.20170101-2

---

alarm/kodi-rbp-git/PKGBUILD

I neglected to add libpulse as a dep which will render systems unable to start `kodi.service` if not installed.

alarm/kodi-rbp-git: update to 17.0rc3.20170114-2

---

alarm/kodi-rbp-git/PKGBUILD

udisks has been officially dropped

alarm/kodi-rbp-git: update to 17.0rc3.20170114-4

---

alarm/kodi-rbp/PKGBUILD

Include dev files and texturepacker - this PKGBUILD is in sync with kodi-git which will highly likely be used for the official Arch kodi PKGBUILD once Ike gets the time to update it.

alarm/kodi-rbp to 17.0-2

---

alarm/kodi-c2/PKGBUILD

```sh
------------------------
Kodi Configuration:
------------------------
Kodi Version:	17.0
git Rev.:	Unknown
Debugging:	No
Profiling:	No
Optimization:	Yes
SWIG Available:	Yes
JRE Available:	Yes
Doxygen Available:	Yes
Crosscomp.:	No
target ARCH:	aarch64
target CPU:	
OpenGLES:	Yes
ALSA:		Yes
DBUS:		Yes
VDPAU:	No
VAAPI:	No
OpenMax:	No
X11:		No
Bluray:	Yes
XSLT scrapers:	Yes
TexturePacker:No
MID Support:	No
ccache:	Yes
ALSA Support:	Yes
PulseAudio:	Yes
Google Test Framework Configured:	Yes
Avahi:	Yes
mDNSEmbedded:	No
Non-free:	Yes
MySQL:	Yes
Webserver:	Yes
libssh support:	Yes
libsmbclient support:	Yes
libnfs client support:Yes
AirPlay support:	Yes
AirTunes support (libshairplay):	Yes
UPnP support:		Yes
Optical drive:	Yes
libudev support:	Yes
libusb support:	No
libcec support:	Yes
lcms2 …
```

alarm/kodi-c2 to 17.0-1

---

extra/firefox/Build-Skia-NEON-code-on-arm64.patch
extra/firefox/PKGBUILD

The Skia graphics library failed to build the
ClampX_ClampY_Procs_neon() function on aarch64, however it still
attempted to link against it, resulting in a linking error. The
patch is used by the Debian Sid Firefox package.

extra/firefox: fix aarch64 build

---

alarm/kodi-rbp/PKGBUILD

Fixes the lzo2 dependency hell.  Builds and runs on RPi2.

alarm/kodi-rbp: update to 17.0-3

---

alarm/kodi-rbp-git/PKGBUILD

Updates to 17.1RC1 and fixes the lzo2 dependency hell. Builds and runs on RPi2.

alarm/kodi-rbp-git: update to 17.1rc1.20170223-1

---

alarm/luajit-git/PKGBUILD

alarm/luajit-git to v2.1.0.beta2.r172.gd3e36e7

---

alarm/cryptodev-dkms/PKGBUILD

Upstream supports kernels >=4.10, but no new release now.
Current version fails to build, because of kernel api changes.

Update cryptodev-dkms to 1.8-6

---

alarm/kodi-rbp/PKGBUILD
alarm/kodi-rbp/hifiberry_digi.patch

alarm/kodi-rbp 
This is basically copy of a pull request #1376.
As a reminder:
> The HiFiBerry Digi+ is a S/PDIF/Toslink output board for the Raspberry Pi (rPi2 and rPi3).
> 
> For years (I found forum topics going back to 2014) kodi is not able to use it as pass-through device for audio output. What that means is, you are not able to get DTS or DolbyD signal in your amp.
> 
> It looks OpenELEC and Osmc already applied the patch, or rather workaround for that issue.
> More info here:
> https://support.hifiberry.com/hc/en-us/community/posts/201845791-Kodi-no-passthrough
> and here
> http://forum.kodi.tv/showthread.php?tid=261778
> 
> Kodi won't apply the patch as in their eyes the problem should be fixed in kernel or by Hifiberry. 
> I really doubt it will be fixed upstream in the near …

alarm/kodi-rbp: spdif/toslink passthrough fix for hifiberry-digi+ card

---

alarm/cryptodev-dkms/PKGBUILD

Follow upstream changes: Fix ablkcipher algorithms usage in v4.8+ kernels.
It looks like cryptodev is working with new kernels again.
```
~$ fgrep crypto /proc/interrupts
28:     520256  main-interrupt-ctrl  22 Edge      f1030000.crypto
~$ openssl speed -evp aes-128-cbc
Doing aes-128-cbc for 3s on 16 size blocks: 27480 aes-128-cbc's in 0.13s
Doing aes-128-cbc for 3s on 64 size blocks: 28800 aes-128-cbc's in 0.10s
[...]
~$ fgrep crypto /proc/interrupts
28:     636846  main-interrupt-ctrl  22 Edge      f1030000.crypto
~$ uname -a
Linux redqueen 4.10.8-1-ARCH #1 PREEMPT Sun Apr 2 00:32:23 MDT 2017 armv5tel GNU/Linux
```
[Edit:]
BTW There is something funny with date on that commit: https://github.com/cryptodev-linux/cryptodev-linux/commit/6818263667ca488f9b1c86e36ea624c4ea1c309f, because …

Update cryptodev-dkms to 1.8-7

---

alarm/kodi-rbp/PKGBUILD

This is a depency of various kodi-addon-* packages. The files that kodi-dev/x86 provides are already included in kodi-rbp.

alarm/kodi-rbp: Provide kodi-dev

---

alarm/kodi-rbp-git/PKGBUILD

This is a depency of various kodi-addon-* packages. The files that kodi-dev/x86 provides are already included in kodi-rbp-git.

alarm/kodi-rbp-git: Provide kodi-dev

---

alarm/kodi-c2/PKGBUILD

The git repository by @phedoreanu seems unmainted and has not been updated for months, so the upstream repo has been switched to the repo by @Owersun which also the current upstream repo for alarm/kodi-c1.
The referenced commit Owersun/xbmc@8cbff508cde50ae3e34d721da895d1a4655f131f works fine on my C2.

alarm/kodi-c2 to 17.1-1

---

alarm/kodi-rbp/PKGBUILD

Bump to new upstream version and fix premissions on `/usr/share/polkit-1/rules.d/` which should be 0750 not 0700.

alarm/kodi-rbp to 17.2-1

---

alarm/kodi-c2/PKGBUILD

Upgrade kodi-c2 to 17.3-1.
Please note that Kodi team may drop autoconf in favor of cmake in the nearest future.

alarm/kodi-c2 to 17.3-1

---

alarm/kodi-rbp/PKGBUILD
alarm/kodi-rbp/fix-python-lib-path.patch

~~Note that this PR is dependent on https://github.com/archlinuxarm/PKGBUILDs/pull/1483~~
EDIT: It should be noted that the hardening-wrapper currently does not support distcc builds.  On my RPi3, it takes over 80 minutes to build this package without distcc compared to about 20 min with distcc.  If no distcc is a deal breaker, let me know and I will adjust the PR to not use the script.

alarm/kodi-rbp to 17.3-2

---

core/linux-aarch64-rc/PKGBUILD

Required to build Mali Utgard kernel driver for meson_drm

core/linux-aarch64-rc: include clocksource in linux-headers

---

alarm/dkms-mali-utgard-meson/PKGBUILD
alarm/dkms-mali-utgard-meson/dkms-mali-utgard-meson.install
alarm/dkms-mali-utgard-meson/dkms.conf

DKMS package for Mali Utgard kernel driver on meson platform

alarm: create dkms-mali-utgard-meson

---

alarm/xf86-video-armsoc-meson/99-mali-meson.conf
alarm/xf86-video-armsoc-meson/PKGBUILD

X.org Mali video driver for Meson platforms

alarm: create xf86-video-armsoc-meson

---

core/linux-odroid-c2/PKGBUILD

Without this, it's not possible to build external modules, since there are lots of cross-arch (arm64->arm) includes.

linux-odroid-c2: include arm arch headers

---

alarm/kodi-c2/PKGBUILD
alarm/kodi-c2/fix-python-lib-path.patch

This updates `kodi-c2` to the latest commit (Owersun/xbmc@cf20c960135f7a9b702afbf7e252ab70cf22a1d9).
Mainline `kodi`'s PKGBUILD has been used as a base to make use of the new CMake build system. Modified for the ODROID-C2:
- Add necessary dependencies (odroid-c2-libgl-fb, odroid-c2-libgl-headers, aml-libs-c2)
- Add permissions file, polkit rules, udev rules and systemd unit
- Set CMake settings: enable AML, disable X11, etc.
Compiles and runs on my ODROID-C2.

alarm/kodi-c2 to 17.4-1

---

alarm/kodi-c2/PKGBUILD

I think it was removed by mistake in 388d8bdadba05a9932c46ab924a84e3c87df4209.

Add the install variable to kodi-c2 PKGBUILD

---

alarm/kodi-rbp/PKGBUILD

Arch switched over to [external ffmpeg](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/kodi&id=8837248d5078a704b59e11f28c8debb23930b985); this PR mirrors that in our package.  [Here] (https://bugs.archlinux.org/task/55675)is the original FS.

alarm/kodi-rbp to 17.4-2

---

alarm/kodi-c2/PKGBUILD

This updates the PKGBUILD to Owersun/xbmc@a3318ca2e106568ada0a9f959238b388a5757943.

alarm/kodi-c2 to 17.4-3

---

alarm/kodi-imx/PKGBUILD

I started having issues in 17.3 with movie playback a while back. I suspect the updated ffmpeg was to blame, but I'm not sure, didn't have time to investigate.
Kodi 17.4 compiles fine, works fine and I no longer have playback issues - everything seems to be back to normal.
I cleaned up a few lines in the PKGBUILD related to crossguid package that were either not necessary or caused problems during compilation.

Updated Kodi IMX to version 17.4

---

alarm/kodi-c2/PKGBUILD

Upgrade to the recent Kodi version. This should also fix dynamic linking issue after upgrading libva to 2.0.0.

alarm/kodi-c2 to 17.5

---

alarm/kodi-c2/PKGBUILD

This updates the `kodi-c2` package to the latest available commit Owersun/xbmc@094825c. Tested on my ODROID-C2 - works fine for me.

alarm/kodi-c2 to 17.6-1

---

core/linux-raspberrypi/PKGBUILD

Replaces the current `7.45.41.23` with `7.45.41.46` which is the first version to fix the ["Broadpwn"](http://blog.exodusintel.com/2017/07/26/broadpwn/) vulnerability according to https://github.com/raspberrypi/linux/issues/1342#issuecomment-321221748.
The two files are the same as already used in `firmware-raspberrypi`.

core/linux-raspberrypi: Update Cypress (Broadcom) firmware

---

core/linux-aarch64/PKGBUILD
core/linux-aarch64/config

I am trying to use Arch Linux ARM on my *NanoPi Neo2* and *OrangePi Zero Plus* boards. Both have Allwinner H5 SoC onboard. You can find my U-Boot packages [here](//github.com/RoEdAl/alarm-uboot-sunxi-aarch64).
Unfortunately USB gadget support is missing in official `linux-aarch64` kernel package. 
I now these boards aren't officially supported and probably never will be but could you enable CONFIG_USB_MUSB_SUNXI in configuration file, please?

linux-aarch64: sunxi - enable USB gadget support

---

alarm/kodi-rbp/PKGBUILD

Kodi doesn't need any gl libs provided by the superfluous deps removed by this commit... it just needs the firmware gl in `/opt/vc/` which is provided by alarm/raspberrypi-firmware.

alarm/kodi-rbp to 17.6-4

---

alarm/kodi-rbp/PKGBUILD

Systems without polkit are unable to the provided udev rules applied.  For example, partial keyboard support in kodi limits functionality making polkit a hard dependency.

alarm/kodi-rbp to 17.6-5

---

alarm/wiringpi/PKGBUILD

It used to be `chmod 4755` in the `PKGBUILD`. Then the `PKGBUILD` was reworked, and the bit got lost, so `gpio` refuses to run.

wiringpi's /usr/bin/gpio lost a suid bit in a recent update

---

aur/cower/PKGBUILD

Update to the likely latest version. Just doing the update, because currently cower needs a libalpm rebuild due to pacman 5.1.0 update.

aur/cower: update to 18

---

alarm/kodi-rbp-git/PKGBUILD
alarm/kodi-rbp-git/kodi.service

* libcec is no longer linked so it's either compiled it as a dep or not compiled it without support (https://github.com/xbmc/xbmc/pull/13926)
* no need to specify the path to lirc's socket path starting with v18

alarm/kodi-rbp-git to 18.0a2.20180621-4

---

alarm/kodi-rbp-git/PKGBUILD
alarm/kodi-rbp-git/fix_fmt_race_condition.patch

* include upstream fmt and crossguid source rather than downloading it at build time
* include a fix for a race condition relating to fmt for users who do not build in a clean chroot (accepted upstream for inclusion in a3 https://github.com/xbmc/xbmc/pull/14215)
* update ffmpeg source

alarm/kodi-rbp-git to 18.0a2.20180621-5

---

core/linux-aarch64/PKGBUILD

This is required to support applying device tree overlays in U-Boot. Tested with `rpi-poe.dtbo` from the Raspberry Pi Foundation tree, on RPi3B+.

linux-aarch64: Generate device tree blobs with symbols

---

core/linux-raspberrypi/PKGBUILD

I believe an error was introduced into the PKGBUILD that caused `/lib/modules/extramodules--raspberrypi/` to have a null inserted between the hyphens.  This PR fixes that and is consistent with other kernel PKGBUILDs.  Let me know if I am missing something.

core/linux-raspberrypi to 4.14.81-2

---

alarm/kodi-rbp-git/PKGBUILD

So it seems kodi-rbp-git needs libnfs as dependency otherwise, kodi bails out at start with this error:
/usr/lib/kodi/kodi-rbpi: error while loading shared libraries: libnfs.so.12: cannot open shared object: No such file or directory
This is a quick fix to let you know of the problem.
I haven't looked at how to do it with cmake variable
RANT:
Why can't we simply create issue and you deal with the problem ? Instead I have to create a pull request just to notify of the problem, and that pull request will never be accepted anyway ? wtf !

kodi-rbp-git needs libnfs as dependency

---

alarm/kodi-rbp3/PKGBUILD
alarm/kodi-rbp3/hifiberry_digi.patch

alarm/kodi-rbp3
Just noticed there's a kodi package specific for rbp3, so this PR is just a copy of #1667 for kodi-rbp.
As a reminder:
> The HiFiBerry Digi+ is a S/PDIF/Toslink output board for the Raspberry Pi (rPi2 and rPi3).
> For years (I found forum topics going back to 2014) kodi is not able to use it as pass-through device for audio output. What that means is, you are not able to get DTS or DolbyD signal in your amp.
> It looks OpenELEC and Osmc already applied the patch, or rather workaround for that issue.
> More info here:
> https://support.hifiberry.com/hc/en-us/community/posts/201845791-Kodi-no-passthrough
> and here
> http://forum.kodi.tv/showthread.php?tid=261778
> Kodi won't apply the patch as in their eyes the problem should be fixed in kernel or by Hifiberry.
> I really …

alarm/kodi-rbp3 - spdif/toslink passthrough fix for hifiberry-digi+ card

---

alarm/kodi-rbp3-addon-visualization-spectrum/PKGBUILD

Add Pi3 port of kodi-rbp-addon-visualization-spectrum, updated to use newer
upstream sources and Pi3-specific optimization.
This has been tested and confirmed to work on a Pi3 B+ running kodi-18.1-1.

Add kodi-rbp3-addon-visualization-spectrum plugin

---

core/linux-aarch64/0001-net-smsc95xx-Allow-mac-address-to-be-set-as-a-parame.patch
core/linux-aarch64/0002-arm64-dts-rockchip-disable-pwm0-on-rk3399-firefly.patch
core/linux-aarch64/0003-arm64-dts-rockchip-add-usb3-controller-node-for-RK33.patch
core/linux-aarch64/0004-arm64-dts-rockchip-enable-usb3-nodes-on-rk3328-rock6.patch
core/linux-aarch64/0005-arm64-dts-rockchip-Fix-vcc_host1_5v-GPIO-polarity-on.patch
core/linux-aarch64/PKGBUILD

Rock64 USB ports are broken since linux-aarch64 4.20.0-1.
This dts patch can bring back USB again, but it might take a long time to be included in upstream kernel release.
So I would like to request to apply it to linux-aarch64 package.
Related links:
* https://archlinuxarm.org/forum/viewtopic.php?f=23&t=13321
* https://lists.infradead.org/pipermail/linux-rockchip/2019-March/023298.html
* https://patchwork.kernel.org/patch/10843309/

core/linux-aarch64: Fix the problem that Rock64 USB ports are broken

---

community/gitlab-runner/PKGBUILD
community/gitlab-runner/config.toml
community/gitlab-runner/gitlab-runner.install
community/gitlab-runner/gitlab-runner.service
community/gitlab-runner/gitlab-runner.sysusers
community/gitlab-runner/gitlab-runner.tmpfiles

The existing package _gitlab-ci-multi-runner_ is outdated for over 2 years and replaced by _gitlab-runner_ in the x86_64 repos. My changes add cross architecture compatibility.

added community/gitlab-runner

---

extra/bind/PKGBUILD

Build of extra/bind for armv5 was broken since v9.13.4, and was disabled in f3ff0f41d
The 9.14.3 upstream release fixed the build on armv5.
This pull request removes the `buildarch`variable to build extra/bind on all platforms.
Since there is no change other than the selection of platforms to build for, I did not see fit to increment the `pkgrel` variable.
I was able to build bind and bind-tools for armv5, and run `named` successfully.

extra/bind: Re-enable armv5 now that upstream fixed the build

---

alarm/kodi-rbp4/99-kodi.rules
alarm/kodi-rbp4/PKGBUILD
alarm/kodi-rbp4/kodi.install
alarm/kodi-rbp4/kodi.service
alarm/kodi-rbp4/polkit.rules

This gbm kodi package for RPi4 can only use sw decoding but does work.  I was able to playback even x265 content with it, but it does require all of the CPU to decode the sample I played.  As you know, I am working with @popcornmix to adapt his https://github.com/popcornmix/xbmc/commits/leia_pi4 fork (enables MMAL decoding for RPi4) which is what LibreLE uses, but it's not ready yet.  This would provide users with RPi4 hardware an option in the meantime.

add kodi-rbp4 18.3-1 (no hw acceleration)

---

alarm/kodi-rbp4/01-fix.in-tree.ffmpeg.paths.for.makechrootpkg.hack.patch
alarm/kodi-rbp4/99-kodi.rules
alarm/kodi-rbp4/PKGBUILD

Enables MMAL for hardware decoding on RPi4 like other kodi-rbp packages.  Major improvement over 18.3-1.

alarm/kodi-rbp4 to 18.3-2

---

alarm/uboot-odroid-c2-mainline/PKGBUILD

**Benefits**
The recent version of U-Boot finally allows HDMI output and simple_fb handover to the Linux kernel on Odroid C2. This PR just updates the version but does not enable the video console.
**Tests done**
- Built manually on Odroid C2 via makepg and installed on Odroid C2 via pacman -U. Board still boots as with the older version. dd if=/dev/mmcblk1 bs=1M count=1 | strings | grep U-Boot shows 2019-07
- Package built using makechrootpkg -c -r "$CHROOT"
- Removed old uboot-odroid-c2-mainline via pacman -R and installed new one. Everything works.
- Removed new package via pacman -R and installed old one from repo. Rebooted and installed new one without removing the old one. Everything works.
Everything tested with MicroSD card as I don't own a eMMC module.
Tested with …

alarm/uboot-odroid-c2-mainline to 2019.07-1

---

alarm/kodi-rbp4/99-kodi.rules
alarm/kodi-rbp4/PKGBUILD

https://github.com/raspberrypi/linux/pull/3111 renames the device nodes which breaks hwacell decoding.  The PR covers both cases.  Eventually, they will drop the argon-* aliases.
Since https://github.com/archlinuxarm/PKGBUILDs/commit/991876d8084a43c69a82aed88d0c03aeae8bea12, the package will be broken without this modification to the udev rules.

alarm/kodi-rbp4 to 18.3-3

---

core/linux-aarch64/PKGBUILD
core/linux-aarch64/config

Add *sun4i-codec* module required by *Orange Pi PC2* board.

core/linux-aarch64 - add sun4i-codec module

---

core/grub/0003-10_linux-detect-archlinux-initramfs.patch
core/grub/0004-add-GRUB_COLOR_variables.patch
core/grub/PKGBUILD
core/grub/grub.default
core/grub/grub.install

Majority of aarch64 boards use u-boot as firmware. Since modern u-boot supports subset of UEFI that is enough to boot grub (and linux) we can actually make generic image even more generic by adding grub into it.
Unfortunately u-boot doesn't support persistent UEFI vars, so grub has to be installed as on removable media, i.e.:
`grub-install --no-nvram --removable --efi-directory=/boot/efi`
With grub installed and configured I was able to boot handcrafted image that contains 2 gpt partitions - 1st ESP mounted into /boot/efi, 2nd rootfs) on two different boards that have u-boot flashed into SPI flash - La Frite and Pine64-LTS.
Since grub-mkconfig expects linux image to be named vmlinuz-* it's also necessary to add `vmlinuz-linux` symlink to `Image.gz` otherwise it won't pick up kernel from …

Add grub package for aarch64

---

alarm/kodi-rbp4/PKGBUILD
alarm/kodi-rbp4/kodi.install
alarm/kodi-rbp4/sysusers.conf
alarm/kodi-rbp4/tmpfiles.conf

PR simplifies `.install` file using systemd natives and pacman hooks.  We can consider similar changes with other kodi-rbpx packages as well.

kodi-rbp4 to 18.5-3

---

alarm/kodi-rbp3/PKGBUILD
alarm/kodi-rbp3/kodi.install
alarm/kodi-rbp3/sysusers.conf
alarm/kodi-rbp3/tmpfiles.conf

Just like https://github.com/archlinuxarm/PKGBUILDs/pull/1758, this simplifies `.install` file using systemd natives and pacman hooks. We can consider similar changes with other kodi-rbpx packages as well.

kodi-rbp3 to 18.5-2

---

core/linux-odroid-n2/PKGBUILD
core/linux-odroid-n2/config

Updated to latest 4.9.216 and enabled usb printing support as in upstream.

core/linux-odroid-n2 to 4.9.216

---

community/gocryptfs/PKGBUILD

`gocryptfs` does require `pandoc` only to build the man pages, so I think it's OK to add it without them.

Add community/gocryptfs

---

alarm/kodi-rbp/PKGBUILD

See https://bugs.archlinux.org/task/63439
Kodi addons like the Netflix addon fail without this dependency.

added python2-pycryptodomex to makedepends

---

core/linux-odroid-n2/PKGBUILD
core/linux-odroid-n2/config

Updated to latest upstream version which also removed CONFIG_AMLOGIC_VIDEOSYNC=y support because it isn't used by the device.

core/linux-odroid-n2 to 4.9.219

---

community/python-xcffib/PKGBUILD

The 'haskell-xcffib' package contains the code generator used to build
python-xcffib from scratch. The stable pypi releases of xcffib just
include the .py file generated by it, so they don't depend on haskell.
---
Reference: https://github.com/tych0/xcffib#installation
I chose to keep a minimal diff with the upstream pkgbuild, but honestly the python2 part stuff could be removed entirely, no one depends on that anymore. I'm also not sure why upstream isn't just using the pypi release, seems to make the whole build process more complicated for little benefit. cc @felixonmars
I guess this is what resulted in the `qtile` package disappearing from the repo. Forum thread for that: https://archlinuxarm.org/forum/viewtopic.php?f=15&t=14247
Not sure if anything special needs to be done to trigger …

Add community/python-xcffib, removed haskell-xcffib dep

---

alarm/dkms-8812au/PKGBUILD
alarm/dkms-8812au/dkms.conf
alarm/dkms-8812au/rtl8812au.conf

Add driver for wifi chipset RTL8812AU which was removed from 5.x kernel series and is actually being sold by companies like ameridroid and hardkernel branded as Wifi Module 5. This driver uses a github repository that has been updated to work with latest 5.x kernels, I have tested it with kernels from 4.9 to 5.7rc and it is more stable/reliable than the one shipped in older kernels.

added alarm/dkms-8812au

---

alarm/kodi-rbp4/PKGBUILD

Kernel 5.4.y deprecated `/dev/argon-hevcmem` in favor of `/dev/rpivid-hevcmem` which breaks the HEVC decoding of this package.  The PR incorporates:
* a patch from upstream to fix this
* imposes a versioned dependency on kernel>=5.4.35

kodi-rbp4 to 18.6-2

---

core/linux-odroid-c2/PKGBUILD

Signed-off-by: graysky <graysky@archlinux.us>

core/linux-odroid-c2 to 3.16.85-1

---

core/linux-aarch64-rc/PKGBUILD
core/linux-aarch64/PKGBUILD
core/linux-am33x/PKGBUILD
core/linux-armv5-rc/PKGBUILD
core/linux-armv5/PKGBUILD
core/linux-armv7-rc/PKGBUILD
core/linux-armv7/PKGBUILD
core/linux-espressobin/PKGBUILD
core/linux-kirkwood-dt/PKGBUILD

All Arch Linux kernel packages have been updated to provide `WIREGUARD-MODULE` since when WireGuard was merged in Linux 5.6.
This pull-requests adds `WIREGUARD-MODULE` to `provides` for the main kernel+modules package in all linux>5.6 kernels.

Make all linux>5.6 packages provide WIREGUARD-MODULE

---

core/linux-aarch64-rc/PKGBUILD
core/linux-aarch64-rc/generate_chromebook_its.sh

This is what we talked about to get stuff smaller. I even successfully tested ;) it on my lazor. I'm confident it'll work pretty far back (everything arm64, excluding veyron, since 32 bit uses a zImage)
Here's some reference: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/281851/
> Changed logic for gathering dtb list to just use a wildcard for boards
> that we're interested in.
> 
> Changed generate_chromebook_its.sh logic to just take in scattered dtb
> files.
> 
> Compressed all input files that go into the .its
> Here are some comparisons:
> * none: `37M`
> * lz4: `17M` < chosen in this commit
> * lzma: `~10M` but boots 1 second slower
> 
> Since it's compressed the .its now had to include external compatible
> properties, used `fdtget .dtb / …

(Compressed .kpart!) core/linux-aarch64-rc to 5.12.rc3-3

---

extra/mesa/PKGBUILD

Mesa 21.2 introduced the PanVK driver,
which is a vulkan driver for panfrost hardware.
While it's not complete yet, package it
as vulkan-panfrost.
Signed-off-by: Dan Johansen <strit@manjaro.org>

extra/mesa to 21.2.1-1.1

---

extra/firefox/PKGBUILD

WebRTC was disabled as part of the 52.0 update, as far as I can see.
The technology is used for video streaming and conferencing.
Many users have successfully built Firefox with WebRTC support,
so I see no reason why it should not be in the official build.
So this removes the disable webrtc mozconfig option,
so it gets enabled in Firefox.
Signed-off-by: Dan Johansen <strit@manjaro.org>

extra/firefox to 92.0.1-1.1

---

core/zstd/PKGBUILD

This issue is breaking boot on non-x86_64 systems: https://bugzilla.redhat.com/show_bug.cgi?id=2035802
This PR adds a core/zstd PKGBUILD that uses a commit from a pending pull request to the zstd GitHub repository to fix it. The patched package works on my machine (passes `check()` and allows the system to boot). I assume this can't be merged exactly like this, but I'm not familiar with Arch Linux ARM protocols, so just tell me what it needs and I'll fix it up (or edit the branch yourselves if you like).

added core/zstd

---

community/yt-dlp/PKGBUILD

Upstream builds `community/yt-dlp` with `pandoc` in makedepends, since `pandoc` is needed to build the docs. However, pandoc is hard to get by on arm(v7) machines, so we avoid it by changing the make target to only build `yt-dlp`, and nothing more, as suggested by the [yt-dlp developers](https://github.com/yt-dlp/yt-dlp#compile).

Add community/yt-dlp

---

core/grub/0003-10_linux-add-archlinuxarm-s-default-kernel-path.patch
core/grub/PKGBUILD

ArchlinuxARM's `linux` package installs kernel image to `/boot/Image`, which will NOT be detected by `grub-mkconfig` by default.
I patched `10_linux` script of `grub` to add the file to being detected kernel image path list.

core/grub: fix detect archlinuxarm's kernel image

---

alarm/dtc145/PKGBUILD

This should be a noop change to the existing dtc145 .pkg files, but in
case you want to recently compile it from scratch you will get this error:
```
/usr/bin/ld: dtc-parser.tab.o:PKGBUILDs/alarm/dtc145/src/dtc-1.4.5/dtc-parser.tab.c:1086: multiple definition of `yylloc'; dtc-lexer.lex.o:PKGBUILDs/alarm/dtc145/src/dtc-1.4.5/dtc-lexer.l:41: first defined here
```
Seems that the usual fix for this (including in the linux kernel) is to
just remove the extra "YYLTYPE yylloc;" line.
Let's do that with a simple sed in our PKGBUILD

alarm/dtc145 Fix yylloc error during compilation

---

extra/firefox/PKGBUILD
extra/firefox/psutil-remove-version-cap.patch
extra/firefox/revert-crossbeam-crates-upgrade.patch

Firefox 98+ fails to draw its window on aarch64.
Upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1757571
Also add a hack to remove the psutil version cap, since otherwise it
fails to build with the latest python-psutil version (for no reason).

extra/firefox: Fix regression on aarch64 (98.0.1-1.1)

---

extra/mesa/PKGBUILD

Mesa 22.0 has an issue where some elements are not rendered
correctly, mostly seen on Plasma.
So apply this[1] patch, which has fixed it in Mesa git main.
1: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/15365
Signed-off-by: Dan Johansen <strit@manjaro.org>

extra/mesa: Add patch to fix rendering issue on Panfrost

---

community/earlyoom/PKGBUILD

Hello, I'm going through the packages I maintain to make sure as many of them can also be built for ARM.
This one optionally depends on `pandoc`, thus the only change.
I also made some changes directly in Arch [community] to `wldash` and `kubernetes` (`kube-apiserver` `kube-controller-manager` `kube-proxy` `kube-scheduler` `kubeadm` `kubectl` `kubelet` `kubernetes-control-plane-common`) that let them compile successfully on ARM (those changes are trivial, don't hurt to have in main repos, and release some maintenance burden from you), would those be automatically picked up and compiled for ALARM?

added community/earlyoom

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/amzn-drivers.install

This pull request adds the amzn-ena-aarch64-dkms PKGBUILD.
This package allows for adding and building the Amazon ENA (Elastic Network Adapter) driver for Gravaton ARM64 instances. Without this driver, ArchLinux ARM instances on AWS do NOT have network connectivity. This package adds the DKMS module to add the driver (since no mainline Arch kernels have support for it).
This package would allow users to build AWS ArchLinuxARM instances without having to manually fetch and build the driver themselves.
Amazon driver source is [here: github.com/amzn/amzn-drivers](https://github.com/amzn/amzn-drivers)
- Package Build tested
- Tested Build in a Clean Chroot
- Tested in an AWS ArchLinuxARM instance
Added this into the "alarm" directory as it is aarch64 specific and is not in any core/extra …

added alarm/amzn-ena-aarch64-dkms

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD

Update to replace the "$(uname -r)" in dkms.conf with "$kernelver" to comply with the DKMS specification and guidelines ([here](https://wiki.archlinux.org/title/DKMS_package_guidelines)).
Explanation of "$kernelver" [here](https://linux.die.net/man/8/dkms)
- Package Build tested
- Tested Build in a Clean Chroot
- Tested in an AWS ArchLinuxARM instance
Package "pkgrel" updated to "2".
Thanks!

alarm/amzn-ena-aarch64-dkms to 2.7.4-2

---

community/fd/PKGBUILD

fd uses jemalloc. jemalloc uses the build system's page size as internal page size and fails if the target's page size is larger (1). Configure the largest possible page size to support every aarch64 system.
1: https://github.com/jemalloc/jemalloc/issues/467
Signed-off-by: Janne Grunau <j@jannau.net>

added community/fd

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/amzn-drivers.install
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to latest release: 2.8.3 (from 2.8.0)
- Fixed a misspelling in the first install message.
Tests:

alarm/amzn-ena-aarch64-dkms to 2.8.3-1

---

community/dtools/PKGBUILD

[Upstream](https://github.com/archlinux/svntogit-community/blob/packages/dtools/trunk/PKGBUILD) uses `dmd` directly, which can only target `x86` and `x86_64`.
This version uses `ldc` which can target more architectures, including ARM.

added community/dtools

---

extra/firefox/PKGBUILD

The issues with webrtc compilation in the previous few versions were caused by a dumb typo in the webrtc patch that was added a few versions ago. This typo concerned a missing source file in the build scripts. This file was only missing for the aarch64 build setup (x86_64, x86 and arm where fine). The patch was made upstream by fedora, and they probably didn't notice the typo since they don't have an official aarch64 variant.
The patch has been removed for 111.0 since the issue has been solved upstream. Firefox 111.0 now compiles with webrtc on aarch64 without any problems. I did check this myself.

extra/firefox: Re-enable webrtc for aarch64

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest release: 2.8.4 (from 2.8.3)
Tests:

alarm/amzn-ena-aarch64-dkms to 2.8.4-1

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest release: 2.8.5 (from 2.8.4)
Tests:

alarm/amzn-ena-aarch64-dkms to 2.8.5-1

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest release: 2.8.8 (from 2.8.5)
Tests:

alarm/amzn-ena-aarch64-dkms to 2.8.8-1

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest release: 2.8.9 (from 2.8.8)
Tests:

alarm/amzn-ena-aarch64-dkms to 2.8.9-1

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest release: 2.9.1 (from 2.8.9)
Tests:

alarm/amzn-ena-aarch64-dkms to 2.9.1-1

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest release: 2.11.0 (from 2.9.1)
Tests:

 alarm/amzn-ena-aarch64-dkms to 2.11.0-1 

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest upstream release: 2.12.0 (from 2.11.0)
Tests:

 alarm/amzn-ena-aarch64-dkms to 2.12.0-1

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest upstream release: 2.12.1 (from 2.12.0)
Tests:

alarm/amzn-ena-aarch64-dkms to 2.12.1-1

---

alarm/firmware-imx/PKGBUILD

Version used on Yocto Project 5.0 LTS (scarthgap): https://layers.openembedded.org/layerindex/recipe/402107/

alarm/firmware-imx to 8.24.r0.fbe0a4c

---

extra/protobuf/PKGBUILD
extra/python-protobuf/.SRCINFO
extra/python-protobuf/PKGBUILD

python-protobuf is a depedendency of several packages, but it was dropped in commit fa75cecf701de0d42eecba9dfb292fe94ea479f5, breaking system updates due to version pinning requirements in the package itself.
This PR re-introduces python-protobuf as a separate PKGBUILD file, without bazel as build dependency, relying on upstream python package tarball releases and usual python toolchains. This alternative toolchain is only available in the python package tarball release and is not present by default in the normal protobuf all-in-one tarball.
Two minor downsides of this solution are:
- When the main protobuf package is updated, this file must be updated alongside due to binary compatibility. Before they were a single file with split packages, now it's two.
- This package will compile its …

re-enable python-protobuf, using a separate PKGBUILD with pypi tarball as source

---

alarm/uboot-sunxi/PKGBUILD

Supersedes #1803, and should bring all of the new features of u-boot to this platform.
I have tested it on both A10-Olinuxino-Lime and A20-Olinuxino-Lime2, and checked that the latter does get gigabit Ethernet enabled.

Bump alarm/uboot-sunxi to 2024.07-1

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest upstream release: 2.13.0 (from 2.12.1)
Tests:

alarm/amzn-ena-aarch64-dkms to 2.13.0-1

---

alarm/uboot-sunxi/PKGBUILD

makedepends was missing python-setuptools.
Fixes build broken by #2045.

alarm/uboot-sunxi to 2024.07-2

---

core/linux-rpi/PKGBUILD

Please see https://github.com/raspberrypi/linux/pull/6524 and https://archlinuxarm.org/forum/viewtopic.php?f=23&t=17131

Include a possible fix for cgroup_enable=memory

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest upstream release: 2.13.1 (from 2.13.0)
Tests:

alarm/amzn-ena-aarch64-dkms to 2.13.1-1

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest upstream release: 2.13.2 (from 2.13.1)
Tests:

alarm/amzn-ena-aarch64-dkms to 2.13.2-1

---

extra/uv/PKGBUILD

Similar to some other packages, uv needs to be built with `JEMALLOC_SYS_WITH_LG_PAGE=16` to work on some aarch64 systems. Upstream is doing this for their official builds (https://github.com/astral-sh/uv/issues/6528) and I confirmed this works on my Apple M1. The PKGBUILD from official Arch doesn't set this, so the `uv` package is broken and crashes. This change should fix that. The rest of the additions are just a copy from Arch's packaging repo.

add package: extra/uv

---

extra/ruff/PKGBUILD

Similar to some other packages, uv needs to be built with `JEMALLOC_SYS_WITH_LG_PAGE=16` to work on some aarch64 systems. Upstream is doing this for their official builds (https://github.com/astral-sh/ruff/pull/4247) and I confirmed this works on my Apple M1.
This is a followup from https://github.com/archlinuxarm/PKGBUILDs/pull/2089

add package: extra/ruff

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest upstream release: 2.13.3 (from 2.13.2)
Tests:

alarm/amzn-ena-aarch64-dkms to 2.13.3-1

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest upstream release: 2.14.0 (from 2.13.3)
Tests:

alarm/amzn-ena-aarch64-dkms to 2.14.0-1

---

alarm/firmware-veyron/PKGBUILD

[This post on the forums](https://archlinuxarm.org/forum/viewtopic.php?f=44&t=15943) describes the situation in detail.
`brcmfmac4354-sdio.bin` is now provided by the `core/linux-firmware` package.
The `brcmfmac4354-sdio.bin` file that is currently provided by the `alarm/firmware-veyron` package was last updated in 2016, but [the firmware has continued to receive updates since then](https://lore.kernel.org/linux-wireless/?q=brcmfmac4354-sdio). This outdated firmware is in a higher priority location in the firmware search path (`/lib/firmware/updates`) than the file provided by the `core/linux-firmware` package (`/lib/firmware`). On my ASUS C201P, my wireless interface only began working after I deleted the outdated file.
This updated PKGBUILD no longer provides `brcmfmac4354-sdio.bin`. …

alarm/firmware-veyron to 1.0-2

---

alarm/rpi-eeprom/PKGBUILD

Update PKGBUILD to latest upstream commit covering new default releases

---

alarm/amzn-ena-aarch64-dkms/PKGBUILD
alarm/amzn-ena-aarch64-dkms/dkms.conf

- Driver updated to the latest upstream release: 2.14.1 (from 2.14.0)
Tests:

alarm/amzn-ena-aarch64-dkms to 2.14.1-1

---

alarm/uboot-odroid-c2-mainline/PKGBUILD

Improves GPT compatibility with bootefi. Fixes:
```
alloc_read_gpt_entries: ERROR: Can't allocate 0X4000 bytes for GPT Entries
GPT: Failed to allocate memory for PTE
```
Tested by booting from SD and eMMC.
------
This is dependent on the meson-tools rebuild in #2137.

alarm/uboot-odroid-c2-mainline to 2025.07-1

---

alarm/meson-tools/PKGBUILD

Rebuild for libcrypto.so soname bump. Fixes failure when building uboot-odroid-c2-mainline:
```
amlbootsig: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

alarm/meson-tools to r32.0a02e2d-2
