- alarm/dkms-mt7610/PKGBUILD
- alarm/dkms-mt7610/dkms-mt7610.install
Added USB_DEVICE(0x148F,0x761a) and compiled with HAS_NATIVE_WPA_SUPPLICANT_SUPPORT=y.
> support for TP_link-TL-WDN5200

- aur/plex-media-server/PKGBUILD
update aur/plex-media-server to 0.9.12.4.1192-1
> aur/plex-media-server to 0.9.12.4.1192-1

- aur/cower/PKGBUILD
Update cower to the latest version.
> aur/cower to 13-1

- alarm/kodi-imx/PKGBUILD
- alarm/kodi-imx/kodi.service
> alarm/kodi-imx - fixed typo in service configuration

- alarm/kodi-rbp-git/PKGBUILD
- aur/dcadec-git/PKGBUILD
> kodi-rbp-git to 16.0a4-Jarvis

- alarm/kodi-rbp-git/PKGBUILD
```
configure: WARNING: unrecognized options: --disable-goom, --disable-xrandr, \
--disable-projectm, --enable-rsxs
```
> alarm/kodi-rbp-git to 16.0b2.20151121-1

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 0.9.15.2.1663-1
> aur/plex-media-server to 0.9.15.2.1663-1

- aur/cower/PKGBUILD
Update cower to 16-1 to reflect upstream changes.
> aur/cower to 16-1

- aur/plex-media-server/PKGBUILD
plex-media-server updated to 0.9.16.4.1911-ee6e505
> aur/plex-media-server updated to 0.9.16.4.1911-ee6e505

- aur/plex-media-server/PKGBUILD
> aur/plex-media-server to 1.0.0.2261

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.0.3.2461
> aur/plex-media-server to 1.0.3.2461

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.1.3.2700
> aur/plex-media-server to 1.1.3.2700

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.1.4.2757
> aur/plex-media-server to 1.1.4.2757

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.2.6.2975
> aur/plex-media-server to 1.2.6.2975

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.2.7.2987
> aur/plex-media-server to 1.2.7.2987

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.2.8.3112
> aur/plex-media-server to 1.2.8.3112

- aur/plex-media-server/PKGBUILD
Previous version was incorrect
> aur/plex-media-server to 1.3.2.3112

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.3.3.3148
> aur/plex-media-server to 1.3.3.3148

- alarm/kodi-rbp-git/PKGBUILD
Update to use upstream supported cmake.  Tested on RPi2 and works!  Lirc works too.
> alarm/kodi-rbp-git: update to 17.0rc3.20170114-1

- alarm/kodi-rbp-git/PKGBUILD
> alarm/kodi-rbp-git: update to 17.0rc3.20170114-3

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.3.4.3285
> aur/plex-media-server to 1.3.4.3285

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.4.3.3433
> aur/plex-media-server to 1.4.3.3433

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.5.3.3580
> aur/plex-media-server to 1.5.3.3580

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.5.4.3596
> aur/plex-media-server to 1.5.4.3596

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.5.5.3634
> aur/plex-media-server to 1.5.5.3634

- core/linux-armv7/linux-armv7-chromebook.install
see also https://github.com/archlinuxarm/PKGBUILDs/commit/70dc420d4f6cd2f5edd9413cf924945e95c98d67 where the same fix was merged
> fiixed path for manual kernel update instructions

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.5.7.4016
> aur/plex-media-server to 1.5.7.4016

- alarm/mali-utgard-meson-libgl/99-mali.rules
- alarm/mali-utgard-meson-libgl/PKGBUILD
- alarm/mali-utgard-meson-libgl/mali.conf
Userspace libraries for GLES acceleration with Mali Utgard GPU on Meson platforms.
> alarm: create mali-utgard-meson-libgl

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.7.5.4035
> aur/plex-media-server to 1.7.5.4035

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.8.1.4139
> aur/plex-media-server to 1.8.1.4139

- alarm/kodi-rbp-git/PKGBUILD
This PR syncs up kodi-rbp-git with kodi-rbp
> alarm/kodi-rbp-git to 17.4rc1.20170811-2

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.8.4.4249
> aur/plex-media-server to 1.8.4.4249

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.9.1.4272
> aur/plex-media-server to 1.9.1.4272

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.9.2.4285
> aur/plex-media-server to 1.9.2.4285

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.9.4.4325
> aur/plex-media-server to 1.9.4.4325

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.9.6.4429
> aur/plex-media-server to 1.9.6.4429

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.9.7.4460
> aur/plex-media-server to 1.9.7.4460

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.9.10.4523
> aur/plex-media-server to 1.9.10.4523

- aur/plex-media-server/PKGBUILD
fix wrong aur/plex-media-server version
> fix wrong aur/plex-media-server version

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.10.1.4602
> aur/plex-media-server to 1.10.1.4602

- alarm/kodi-odroid/PKGBUILD
Tested on my Odroid U3
P.S. I couldn't get CMake configs working with Mali-EGL just yet.
> alarm/kodi-odroid to 17.6

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.11.3.4803
> aur/plex-media-server to 1.11.3.4803

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.12.0.4829
> aur/plex-media-server to 1.12.0.4829

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.12.1.4885
> aur/plex-media-server to 1.12.1.4885

- alarm/kodi-rbp-git/PKGBUILD
Make polkit a hard dep like https://github.com/archlinuxarm/PKGBUILDs/pull/1576
> alarm/kodi-rbp-git to 18.0a1.20180310-2

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.12.2.4929
> aur/plex-media-server to 1.12.2.4929

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.13.0.5023
> aur/plex-media-server to 1.13.0.5023

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.13.2.5154
> aur/plex-media-server to 1.13.2.5154

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.13.4.5251
> aur/plex-media-server to 1.13.4.5251

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.13.4.5271
> aur/plex-media-server to 1.13.4.5271

- core/linux-aarch64-rc/PKGBUILD
- core/linux-aarch64-rc/config
Recommended in https://wiki.archlinux.org/index.php/Zswap.
> Enable z3fold allocator

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.13.5.5291
> aur/plex-media-server to 1.13.5.5291

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.13.8.5395
> aur/plex-media-server to 1.13.8.5395

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.14.0.5470
> aur/plex-media-server to 1.14.0.5470

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.14.1.5488
> aur/plex-media-server to 1.14.1.5488

- alarm/kodi-rbp/PKGBUILD
Rebuild against new mariadb libs
> alarm/kodi-rbp to 17.6-7

- alarm/kodi-c1/PKGBUILD
Rebuild against new mariadb-libs. 
FYI @erikfleischer @kmihelich
> Update kodi-c1: libmariadbclient → mariadb-libs

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.15.2.793
> aur/plex-media-server to 1.15.2.793

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.15.3.876
> aur/plex-media-server to 1.15.3.876

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.15.4.993
> aur/plex-media-server to 1.15.4.993

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.15.4.994
> aur/plex-media-server to 1.15.4.994

- alarm/kodi-rbp3/PKGBUILD
Fixes [FS#62552](https://bugs.archlinux.org/task/62552)
> alarm/kodi-rbp3 to 18.2-2

- alarm/kodi-rbp/PKGBUILD
Fixes [FS#62552](https://bugs.archlinux.org/task/62552)
> alarm/kodi-rbp to 18.2-2

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.15.6.1079
> aur/plex-media-server to 1.15.6.1079

- aur/plex-media-server/PKGBUILD
aur/plex-media-server to 1.16.0.1226
> aur/plex-media-server to 1.16.0.1226

- alarm/kodi-c2/PKGBUILD
- alarm/kodi-c2/kodi.service
> alarm/kodi-c2 - fixed typo in service configuration

- alarm/kodi-rbp4/PKGBUILD
upstream tagged a different commit and rebased without remaining, also minor change to dep
> alarm/kodi-rbp4 to 18.4-2

- alarm/kodi-rbp/PKGBUILD
- alarm/kodi-rbp/kodi.install
- alarm/kodi-rbp/sysusers.conf
- alarm/kodi-rbp/tmpfiles.conf
Just like https://github.com/archlinuxarm/PKGBUILDs/pull/1758, this simplifies .install file using systemd natives and pacman hooks.
> kodi-rbp to 18.5-2

- alarm/kodi-c1/PKGBUILD
- alarm/kodi-c1/kodi.install
- alarm/kodi-c1/sysusers.conf
- alarm/kodi-c1/tmpfiles.conf
Just like https://github.com/archlinuxarm/PKGBUILDs/pull/1758, this simplifies .install file using systemd natives and pacman hooks.
> kodi-c1 to 17.6-6

- alarm/cryptodev-dkms/PKGBUILD
> alarm/cryptodev-dkms to 1.10-4

- alarm/cryptodev-dkms/PKGBUILD
> alarm/cryptodev-dkms to 1.11-1

- alarm/cryptodev-dkms/PKGBUILD
> alarm/cryptodev-dkms to 1.12-1

- extra/mesa/PKGBUILD
See this MR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/15120
And this issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5758
Unlikely to be merged into 21.3 branch
Signed-off-by: Dan Johansen <strit@manjaro.org>
> extra/mesa: Add patch to fix xwayland on panfrost

- extra/uasm/.SRCINFO
- extra/uasm/PKGBUILD
- extra/uasm/repro-date.patch
- extra/uasm/uasm-nocolor
I haven't tried this on armv7, but hopefully it just works. Importing this will help get 7zip into ALARM.
> import of uasm
